### ISSUE TITLE
UnicodeEncodeError without UTF-8 local 

### ISSUE THREAD

**Issue by tuxlife** [zalando-stups/stups-cli-support#2]
`Writing config for Più.. OK` works only with UTF-8

```
root@0748f4470c35:/# stups

  ___ _____ _   _ ___  ___
 / __|_   _| | | | _ \/ __| by ZALANDO
 \__ \ | | | |_| |  _/\__ \
 |___/ |_|  \___/|_|  |___/

 STUPS - To Unleash Penguin Swarms

 Homepage:      https://stups.io
 Documentation: https://docs.stups.io
 GitHub Repos:  https://github.com/zalando-stups

Do you want to configure the STUPS CLI tools now? [Y/n]: 
Please enter your STUPS domain (e.g. "stups.example.org"): xyz
Trying to autoconfigure mai.. OK
Trying to autoconfigure zign.. OK
Checking https://xyz.. OK
Checking https://xyz.. OK
Checking https://xyz.. OK
Writing global config.. OK
Writing config for Pier One.. OK
Traceback (most recent call last):
  File "/usr/local/bin/stups", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.4/dist-packages/stups/cli.py", line 28, in main
    stups_cli.config.configure(domain)
  File "/usr/local/lib/python3.4/dist-packages/stups_cli/config.py", line 94, in configure
    with Action('Writing config for Pi\xf9..'):
  File "/usr/local/lib/python3.4/dist-packages/clickclick/console.py", line 92, in __enter__
    action(self.msg, **self.msg_args)
  File "/usr/local/lib/python3.4/dist-packages/clickclick/console.py", line 44, in action
    secho(msg.format(**kwargs), nl=False, bold=True)
  File "/usr/local/lib/python3.4/dist-packages/clickclick/console.py", line 40, in secho
    click.secho(*args, **kwargs)
  File "/usr/local/lib/python3.4/dist-packages/click/termui.py", line 417, in secho
    return echo(style(text, **styles), file=file, nl=nl, err=err, color=color)
  File "/usr/local/lib/python3.4/dist-packages/click/utils.py", line 314, in echo
    file.write(message)
UnicodeEncodeError: 'ascii' codec can't encode character '\xf9' in position 25: ordinal not in range(128)
```

**Comment by akauppi** [comment]
This is something that OS X users of STUPS face "out of the box":

```
...
UnicodeDecodeError: 'utf-8' codec can't decode bytes in position 11-12: invalid continuation byte
```

It's easy to [bypass](http://stups.readthedocs.org/en/latest/user-guide/local-setup.html#local-environment), but I hope the tools themselves would be okay with OS X default locale.
